name: coref_spanbert
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip:
    - pandas
    - allennlp
    - allennlp-models
    - tqdm
    - ipykernel
    - ipywidgets 
    - jupyter
